version: '3.8'
services:
  api:
    container_name: sairahut-api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
      cache_from:
        - node:20-slim
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://sairahut-mongo/sit-sairahut-uwt-dev
    depends_on:
      - mongo
  client:
    container_name: sairahut-client
    image: client
    build:
      context: .
      dockerfile: Dockerfile
      target: client
      cache_from:
        - node:20-slim
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - api
  mongo:
    container_name: sairahut-mongo
    image: mongo:4.0
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
