version: '3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongo-container
    image: mongo:4.0
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
